### ISSUE TITLE
DATABASE: Create Data Models in Rails 

### ISSUE THREAD

**Issue by chill5018** [jferreira/MS-V1_Media-Sifter_BACKEND-RAILS#2]
## Tasks 
- [ ] Take EER diagram, to scaffold Rails objects (basic attributes --> blue dots)
- [ ] Once all objects are added, add relationships (red dots) 
- [ ] Run `rails db:migrate` - to create all the tables once the models look ready

#### Note:
_Note: if `rails g scaffold MODEL ....` does not work, run `spring stop`. This will allow rails g scaffold to do its magic_

#### Estimated Date of Completion: 
12th of August 2017
